language: c

sudo: false

env:
 global:
  - UNAME=$(uname -s)

matrix:
  include:
    - os: linux
    - os: linux
      addons:
        apt:
          packages:
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
      env: 
       - HOST=i686-w64-mingw32-
       - LIBS=-lpthread
       - LDFLAGS="-Wl,-l:pd.dll -Wl,--enable-auto-image-base"
       - UNAME=MINGW
    - os: osx
      env:
        - CFLAGS="-arch x86_64"
    - os: osx
      env:
        - CFLAGS="-arch i386"

before_script:
 - curl -O "http://msp.ucsd.edu/Software/pd-0.46-7.msw.zip" && unzip pd-0.46-7.msw.zip

script:
- make -C iemnet UNAME="${UNAME}" CC="${HOST}${CC}" LDFLAGS="${LDFLAGS}" LIBS="${LIBS}" PD_PATH="${TRAVIS_BUILD_DIR}/pd" PD_INCLUDE="${TRAVIS_BUILD_DIR}/pd/src"
