language: c

matrix:
  include:
    - os: linux
    - os: osx
      env:
        - CFLAGS="-arch x86_64"
    - os: osx
      env:
        - CFLAGS="-arch i386"

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq puredata-dev

script:
- make

#addons:
#  apt:
#    packages:
#      - gcc-mingw-w64-i686
